<a href="https://colab.research.google.com/github/vanessamr/POO/blob/main/challenge_NumPy_VMR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### (2020) Gonzalo G. Peraza Mues

# Numpy Exercises

Vamos a resolver algunos ejercicios sencillos con Numpy.

In [ ]:
import numpy as np

# Definimos un vector
x=np.array([1, 2, 3, 4, 5])
# Y una matriz
m=np.array([[1, 2, 3],[4, 5, 6,], [7, 8, 9]])

In [ ]:
print(x)

[1 2 3 4 5]


In [ ]:
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Una operación común que querrá hacer con
vectores o matrices es sumar cada elemento.
La notación puede dar miedo, pero en realidad es
bastante simple:
$$
\sum_{i,j = 1}^n m_{ij}
$$
El símbolo $\Sigma$ es $\sigma$ mayúscula
y se llama "sigma". Significa que para alguna matriz $m$, donde $i$ representa una fila y $j$ representa una columna, sume todos los elementos. $n$ se refiere al número de elementos de la variable $m$.

Aunque puede implementar esta operación usando un bucle for, NumPy lo hace fácil al proporcionar un método `sum`.

Intente implementarlo ahora `m.sum ()`, debes obetener el valor 45.

In [ ]:
a= np.sum(m)
a

45

Otra operación común es multiplicar cada
valor en un vector o matriz. Esto parece
esto:
$$
\prod_{i,j=1}^n m_{ij}
$$

El símbolo $\Pi$ es un símbolo $\pi$ mayúscula, pronunciado "pi". Implemente esta ecuación de manera similar usando la función `prod`, debe obtener 362880. 

In [ ]:
np.prod(m)

362880

¡Estupendo! Ahora está listo para implementar algunos
ecuaciones básicas! Empecemos con la
media aritmética:
$$
\bar{x} = \frac{1}{n}\times \sum_{i=1}^n x_i
$$

Esto simplemente significa agregar cada elemento de un
lista y dividiendo el resultado por el número de
elementos en $ x $. Una barra sobre una variable ($ \bar {x} $) se refiere a un tipo de media.

**Hint:** Puedes obtener la cantidad de elementos
en una matriz en NumPy con `x.size` ..


Comúnmente conocido como: PROMEDIO

In [ ]:
# Calcula la MEDIA ARITMETICA y guardala en la variable 'mean' 
mean = 0

### Codea aqui
#print(f'Calulaste una media de {mean}, debería ser 3.0')
np.size(m)
np.mean(m)

5.0

In [ ]:
np.mean(x)

3.0

In [ ]:
mean=x.sum()/x.size
mean

3.0

In [ ]:
mean= a/9
mean

5.0

¡Buen trabajo! Ahora implementemos algo conocido
como la norma Frobenius (Euclidean norm, norma de un vector, distancia entre dos puntos):
$$
\Vert m \Vert_F = \left(
    \sum_{i,j=1}^n m_{ij}^2
    \right)^{1/2}
$$

**Hint:** Puede implementar esto de varias formas, usando operadores (`**`), funciones (`np.sqrt`) y métodos (` .sum`).

In [ ]:
# Calcula la NORMA DE FROBENIUS y guardala en la variable f_norm
f_norm = 0

### Codea Aqui

f_norm=np.sqrt((m**2).sum())
#print(f'La norma Frobenius que encontraste es {round(f_norm, 4)}, y esta debe de ser 16.8819')
f_norm

16.881943016134134

¡Perfecto! Ahora, para su desafío final, implementemos la desviación estándar:
$$
\sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}
$$

Recuerde que $ \bar {x} $ se refiere a la media aritmética de $ x $.
En lugar de implementarlo desde cero, simplemente puede llamar a `x.mean ()`.


In [15]:
# Calcula la DESVIACION ESTANDAR y guardala en la variable 'sd'
sd = 0

### Codea Aqui
sd= np.sqrt(np.sum((x-x.mean()**2)/x.size-1))
sd
#print(f'Has encontrado que la desviacion estandar es {round(sd, 4)}, y justo esta debia de ser 1.5811')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


nan

Como un último reto, vamos a calcular una matriz de distancias en numpy.
Implementa una función que tome como entrada una matrix de datos, donde cada fila es una observación y cada columna una variable, y devuelva otra matriz, la matriz de distancias.

La matriz de distancias es muy utilizado en algoritmos de aprendizaje y tiene la siguiente forma:

$$
D = \begin{pmatrix}
d(x_1,x_1) & d(x_1,x_2) & \dots & d(x_1,x_n)\\
d(x_2,x_1) & d(x_2,x_2) & \dots & d(x_2,x_n)\\
\vdots & \vdots & \ddots & \vdots\\
d(x_n,x_1) & d(x_n,x_2) & \dots & d(x_n,x_n)
\end{pmatrix}
$$

Es una matrix NxN, donde N es el número de observaciones en la matriz de datos. Cada entrada de la matriz $d(x_i,x_j)$ es la distancia entre observación $i$ y $j$, y se calcula como

$$
d(x_i,x_j) = \sqrt{\sum_l (x_{il} - x_{jl})^2}
$$

Es decir, resta cada variable, elemento por elemento, de los vectores de observación, eleva las restas al cuadrado y suma todas. Al final saca la raíz. Esta es la distancia euclidiana o norma-2.

Una de las maneras mas eficientes en computo, aunque no en memoria, es hacer un broadcast en 3D, aunque no es la única manera.

In [ ]:
def distance_matrix(X):
    """Retorna la DISTANCIA EUCLIDIANA entre los puntos (datos) de la matriz X. """
    
    # Codea aquí


    return D

## References
- Adapted from: https://mathtocode.com/ by Vernon Thommeret